version: '3'
services:
  efrizer-sql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: unless-stopped
    environment: 
      - ACCEPT_EULA=Y
      - SA_PASSWORD=QWElkj132!
      - MSSQL_PID=Developer
    ports:
      - 1401:1433
    networks: 
      - efrizernet
    
  efrizer-api:
    restart: unless-stopped
    build:
      context: .
    environment: 
      - ConnectionStrings:DefaultConnection=Server=efrizer-sql, 1433; Database=eFrizerDB; User=sa; Password=QWElkj132!; ConnectRetryCount=0
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 5010:5010
    networks: 
      - efrizernet
    links:
      - efrizer-sql
    depends_on: 
      - efrizer-sql

networks: 
  efrizernet:
    driver: bridge