version: '3'

services:
  efrizer-sql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    deploy:  
      resources:
        limits:
          memory: 2g
    restart: unless-stopped
    environment: 
      - ACCEPT_EULA=Y
      - SA_PASSWORD=QWElkj132!
      - MSSQL_PID=Developer
    ports:
      - 1433:1433
    networks: 
      - efrizernet
    
  efrizer-api:
    restart: unless-stopped
    build:
      context: .
    image: amaracr.azurecr.io/efrizer-api
    environment: 
      - ConnectionStrings__DefaultConnection=Server=efrizer-sql, 1433; Database=eFrizerDB; User=sa; Password=QWElkj132!; ConnectRetryCount=0
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:5010;http://+:5000
      - ASPNETCORE_Kestrel__Certificates__Default__Password=1234
      - ASPNETCORE_Kestrel__Certificates__Default__Path=efrizer_cert.pfx
    volumes:
      - amarstorage:/aspnet/https
    ports:
      - 5000:5000
      - 5010:5010
    networks: 
      - efrizernet
    links:
      - efrizer-sql
    depends_on: 
      - efrizer-sql

networks: 
  efrizernet:
    driver: bridge    

volumes:
  amarstorage:
    driver: azure_file
    driver_opts:
      share_name: amaracishare
      storage_account_name: amarseminarskistorage
    
