version: '3'
services:
  efrizer-sql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: unless-stopped
    environment: 
      - ACCEPT_EULA=Y
      - SA_PASSWORD=QWElkj132!
      - MSSQL_PID=Developer
    ports:
      - 1401:1433
    networks: 
      - efrizernet
    
  efrizer-api:
    restart: unless-stopped
    build:
      context: .
    environment: 
      - ConnectionStrings:DefaultConnection=Server=efrizer-sql, 1433; Database=eFrizerDB; User=sa; Password=QWElkj132!; ConnectRetryCount=0
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=1234
      - ASPNETCORE_Kestrel__Certificates__Default__Path=efrizer_cert.pfx
    volumes:
      - ~/.aspnet/https:/https:ro
    ports:
      - 80:80
      - 443:443
    networks: 
      - efrizernet
    links:
      - efrizer-sql
    depends_on: 
      - efrizer-sql

networks: 
  efrizernet:
    driver: bridge